[env:native]
platform = native
test_build_src = yes
build_flags = 
    -std=c++11
    ; Recommended for fakeit
    -O0
    -D USBCON
debug_test = *
build_type = debug
debug_build_flags = -O0 -g
lib_deps = 
    https://github.com/adbancroft/SimpleArduinoFake

[env:native_mingw64]
extends = env:native
build_flags =
    ${env:native.build_flags} 
    ; Required to prevent 'undefined reference' & 'too many sections' errors
    -Wa,-mbig-obj
debug_build_flags =
    ${env:native.debug_build_flags} 
    ; Required to prevent 'undefined reference' & 'too many sections' errors
    -Wa,-mbig-obj

