[env:native]
platform = native
test_build_src = yes
build_flags = 
    -std=c++11
    ; Recommended for fakeit
    -O1
    -D USBCON
debug_test = *
build_type = debug
debug_build_flags = -O1 -g
lib_deps = 
    https://github.com/adbancroft/SimpleArduinoFake