[env:Win32]
platform = windows_x86
test_build_src = yes
build_flags = -std=c++11 -Wno-attributes -DWIN32
debug_test = *
build_type = debug
lib_deps = 
    ; https://github.com/FabioBatSilva/ArduinoFake
    c:/dev/ArduinoFake